version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"
