version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    working_directory: ~/repo

    parallelism: 4

    steps:
      - checkout
      # Download and cache dependencies
      - setup_remote_docker:
          version: 18.06.0-ce

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: docker build -t cesar18pena/ts-boilerplate-api -f Dockerfile.dev .

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: docker run cesar18pena/ts-boilerplate-api npm run lint
      - run: docker run cesar18pena/ts-boilerplate-api npm run test
