version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10,
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: docker build -t cesar18pena/ts-boilerplate-api -f Dockerfile.dev .
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests
      - run: npm run build
      - run: npm run test
